# docker-compose.yml

# Reference compose file version 3
version: "3"
services:
    react-app:
        build: .
        volumes:
          - ./:/app
          - /app/node_modules
        ports:
          - 5173:5173

